
package eu.x_road.emta_v6;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
//import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import eu.x_road.emta_v6.WebService;

/**
 * This class was generated by Apache CXF 3.2.0 2020-02-15T00:57:43.269+02:00
 * Generated source version: 3.2.0
 * 
 */
public final class WebServiceInterface_Port_Client {

	private static final QName SERVICE_NAME = new QName("http://emta-v6.x-road.eu", "webService");

	private WebServiceInterface_Port_Client() {
	}

	public static void main(String args[]) throws java.lang.Exception {
		URL wsdlURL = WebService.WSDL_LOCATION;
		if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
			File wsdlFile = new File(args[0]);
			try {
				if (wsdlFile.exists()) {
					wsdlURL = wsdlFile.toURI().toURL();
				} else {
					wsdlURL = new URL(args[0]);
				}
			} catch (MalformedURLException e) {
				e.printStackTrace();
			}
		}

		WebService ss = new WebService(wsdlURL, SERVICE_NAME);
		WebServiceInterface port = ss.getPort();

		{
			System.out.println("Invoking xteeFieAndmed...");
			eu.x_road.emta_v6.PersonalIdentityCode _xteeFieAndmed_keha = null;
			eu.x_road.xsd.identifiers.XRoadClientIdentifierType _xteeFieAndmed_clientVal = null;
			javax.xml.ws.Holder<eu.x_road.xsd.identifiers.XRoadClientIdentifierType> _xteeFieAndmed_client = new javax.xml.ws.Holder<eu.x_road.xsd.identifiers.XRoadClientIdentifierType>(
					_xteeFieAndmed_clientVal);
			eu.x_road.xsd.identifiers.XRoadServiceIdentifierType _xteeFieAndmed_serviceVal = null;
			javax.xml.ws.Holder<eu.x_road.xsd.identifiers.XRoadServiceIdentifierType> _xteeFieAndmed_service = new javax.xml.ws.Holder<eu.x_road.xsd.identifiers.XRoadServiceIdentifierType>(
					_xteeFieAndmed_serviceVal);
			java.lang.String _xteeFieAndmed_idVal = "";
			javax.xml.ws.Holder<java.lang.String> _xteeFieAndmed_id = new javax.xml.ws.Holder<java.lang.String>(
					_xteeFieAndmed_idVal);
			java.lang.String _xteeFieAndmed_protocolVersionVal = "";
			javax.xml.ws.Holder<java.lang.String> _xteeFieAndmed_protocolVersion = new javax.xml.ws.Holder<java.lang.String>(
					_xteeFieAndmed_protocolVersionVal);
			java.lang.String _xteeFieAndmed_userIdVal = "";
			javax.xml.ws.Holder<java.lang.String> _xteeFieAndmed_userId = new javax.xml.ws.Holder<java.lang.String>(
					_xteeFieAndmed_userIdVal);
			java.lang.String _xteeFieAndmed_issueVal = "";
			javax.xml.ws.Holder<java.lang.String> _xteeFieAndmed_issue = new javax.xml.ws.Holder<java.lang.String>(
					_xteeFieAndmed_issueVal);
			javax.xml.ws.Holder<eu.x_road.emta_v6.PersonalIdentityCode> _xteeFieAndmed_paring = new javax.xml.ws.Holder<eu.x_road.emta_v6.PersonalIdentityCode>();
			javax.xml.ws.Holder<eu.x_road.emta_v6.XteeFieAndmedResponseType> _xteeFieAndmed_keha2 = new javax.xml.ws.Holder<eu.x_road.emta_v6.XteeFieAndmedResponseType>();
			((javax.xml.ws.BindingProvider) port).getRequestContext().put(

					javax.xml.ws.BindingProvider.ENDPOINT_ADDRESS_PROPERTY,

					"http://localhost:8080/xTeeFieAndmed/services/PortImpl");
			

			port.xteeFieAndmed(_xteeFieAndmed_keha, _xteeFieAndmed_client, _xteeFieAndmed_service, _xteeFieAndmed_id,
					_xteeFieAndmed_protocolVersion, _xteeFieAndmed_userId, _xteeFieAndmed_issue, _xteeFieAndmed_paring,
					_xteeFieAndmed_keha2);

			System.out.println("xteeFieAndmed._xteeFieAndmed_client=" + _xteeFieAndmed_client.value);
			System.out.println("xteeFieAndmed._xteeFieAndmed_service=" + _xteeFieAndmed_service.value);
			System.out.println("xteeFieAndmed._xteeFieAndmed_id=" + _xteeFieAndmed_id.value);
			System.out.println("xteeFieAndmed._xteeFieAndmed_protocolVersion=" + _xteeFieAndmed_protocolVersion.value);
			System.out.println("xteeFieAndmed._xteeFieAndmed_userId=" + _xteeFieAndmed_userId.value);
			System.out.println("xteeFieAndmed._xteeFieAndmed_issue=" + _xteeFieAndmed_issue.value);
			System.out.println("xteeFieAndmed._xteeFieAndmed_paring=" + _xteeFieAndmed_paring.value);
			System.out.println("xteeFieAndmed._xteeFieAndmed_keha2=" + _xteeFieAndmed_keha2.value);

		}

		System.exit(0);
	}

}
